python_project/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url


app_name = "accounts"

urlpatterns = [
    path('profile', views.ProfileView.as_view(), name="profile"),

    # Django auth
    path('login', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.SignUpView.as_view(), name='signup'),
]

python_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views, settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('python_project.apps.public.urls')),
    path("accounts/", include('python_project.apps.accounts.urls')),
    ]

# here we append thats why += we grab media url and seting it to the imagess folder then
# we add this to media root which points to images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div>
        {% for product in products %}
            <h6><strog>{{ product.price }}</strog></h6>
        {% endfor %}
    </div>

{% endblock content %}

{#{% extends 'store/main.html' %}#}
{#{% load static %}#}
{#{% block content %}#}
{#	<div class="row">#}
{#		{% for product in products %}#}
{#		<div class="col-lg-4">#}
{#			<img class="thumbnail" src="{{product.imageURL}}">#}
{#			<div class="box-element product">#}
{#				<h6><strong>{{product.product_name}}</strong></h6>#}
{#				<hr>#}
{##}
{#				<button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>#}
{##}
{#				<a class="btn btn-outline-success" href="#">View</a>#}
{#				<h4 style="display: inline-block; float: right"><strong>${{product.price}}</strong></h4>#}
{##}
{#			</div>#}
{#		</div>#}
{#		{% endfor %}#}
{#	</div>#}
{##}
{#{% endblock content %}#}

templates/admin2.html
<!DOCTYPE html>
<html>
<body>

<h1>Admin page</h1>
<h2>All the coments</h2>
{% for el in comments %}
    <a>{{el.user}} &nbsp;&nbsp;&nbsp; </a>
        <br>
    <a href="/delete/{{ el.id }}"> Delete </a>
{% endfor %}
<br>
<h2>All the dresses</h2>
{% for el in dress %}
    <a>{{ el.product_name }} &nbsp;&nbsp;&nbsp; </a>
    <a>   </a>
    <a>{{ el.price }}</a>
    <a>$ &nbsp;&nbsp;&nbsp;</a>
{#    <a href="{% url 'delete' el.id %}">Delete</a>#}
    <br>
{% endfor %}

</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Ecom</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<script type="text/javascript">
		var user = '{{request.user}}'

		function getToken(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getToken('csrftoken')

		function getCookie(name) {
		    // Split cookie string and get all individual name=value pairs in an array
		    var cookieArr = document.cookie.split(";");

		    // Loop through the array elements
		    for(var i = 0; i < cookieArr.length; i++) {
		        var cookiePair = cookieArr[i].split("=");

		        /* Removing whitespace at the beginning of the cookie name
		        and compare it with the given string */
		        if(name == cookiePair[0].trim()) {
		            // Decode the cookie value and return
		            return decodeURIComponent(cookiePair[1]);
		        }
		    }

		    // Return null if not found
		    return null;
		}
		var cart = JSON.parse(getCookie('cart'))

		if (cart == undefined){
			cart = {}
			console.log('Cart Created!', cart)
			document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
		}
		console.log('Cart:', cart)

	</script>

</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	      </li>

	    </ul>

	  </div>
	</nav>

     <div class="container">
            <br>
            {% block content %}


            {% endblock content %}
         </div>


{#	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>#}
{##}
{#	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>#}
{##}
{#	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>#}
{##}
{#	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>#}
</body>
</html>

templates/cart.html
{##}
{##}
{#{% block title %}Contact{% endblock %}#}
{##}
{##}
{##}
{##}
{#   {% for item in items %}#}
{##}
{#       <div ><p>{{ item.Women_Shirts_product.product_name }}</p></div>#}
{#       <div ><p>{{ item.Women_Skirts_product.product_name }}</p></div>#}
{#       <div ><p>{{ item.Women_Pants_product.product_name }}</p></div>#}
{#       <div ><p>{{ item.Women_Dresses_product.product_name }}</p></div>#}
{#       <div ><p>{{ item.Mans_Sweaters_product.product_name }}</p></div>#}
{#       <div ><p>{{ item.Mans_Shirts_product.product_name }}</p></div>#}
{#       <div ><p>{{ item.Mans_Pants_product.product_name }}</p></div>#}
{#       <div ><p>{{ item.Mans_DressShirts_product.product_name }}</p></div>#}
{##}
{#   {% endfor %}#}
{##}

{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">


				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Total:<strong> ${{order.get_cart_total|floatformat:2}}</strong></h5></th>
						<th>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
                    {% for item in items %}
                        {% if  Women_Pants_product.product_name == ""%}
                        {% else %}
                            <div class="cart-row">
                                <div ><img class="row-image" src="{{item.product.image.url}}" alt=""></div>
                                <div style="flex:2"><p>{{item.Women_Shirts_product.product_name}}</p></div>
                                <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
                                <div style="flex:1">
                                    <p class="quantity">{{item.quantity}}</p>
                                    <div class="quantity">
                                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

                                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                                    </div>
                                </div>
                                <div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
                            </div>
                        {% endif %}
                        {% if  Women_Pants_product.product_name == ""%}
                        {% else %}
                            <div class="cart-row">
                                <div ><img class="row-image" src="{{item.product.imageURL}}"></div>
                                <div style="flex:2"><p>{{item.Women_Skirts_product.product_name}}</p></div>
                                <div style="flex:1"><p>${{item.Women_Skirts_product.price|floatformat:2}}</p></div>
                                <div style="flex:1">
                                    <p class="quantity">{{item.quantity}}</p>
                                    <div class="quantity">
                                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

                                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                                    </div>
                                </div>
                                <div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
                            </div>
                        {% endif %}
                        {% if  Women_Pants_product.product_name == ""%}

                        {% else %}
                            <div class="cart-row">
                                <div ><img class="row-image" src="{{item.product.imageURL}}"></div>
                                <div style="flex:2"><p>{{Women_Pants_product.product_name}}</p></div>
                                <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
                                <div style="flex:1">
                                    <p class="quantity">{{item.quantity}}</p>
                                    <div class="quantity">
                                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

                                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                                    </div>
                                </div>
                                <div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
                            </div>
                        {% endif %}
                        {% if  Women_Pants_product.product_name == ""%}
                        {% else %}
                            <div class="cart-row">
                                <div ><img class="row-image" src="{{item.product.imageURL}}"></div>
                                <div style="flex:2"><p>{{item.Women_Dresses_product.product_name}}</p></div>
                                <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
                                <div style="flex:1">
                                    <p class="quantity">{{item.quantity}}</p>
                                    <div class="quantity">
                                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

                                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                                    </div>
                                </div>
                                <div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
                            </div>
                        {% endif %}
                        {% if  Women_Pants_product.product_name == ""%}
                        {% else %}
                            <div class="cart-row">
                                <div ><img class="row-image" src="{{item.product.imageURL}}"></div>
                                <div style="flex:2"><p>{{item.product.name}}</p></div>
                                <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
                                <div style="flex:1">
                                    <p class="quantity">{{item.quantity}}</p>
                                    <div class="quantity">
                                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

                                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                                    </div>
                                </div>
                                <div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
                            </div>
                        {% endif %}
                        {% if  Women_Pants_product.product_name == ""%}
                        {% else %}
                            <div class="cart-row">
                                <div ><img class="row-image" src="{{item.product.imageURL}}"></div>
                                <div style="flex:2"><p>{{item.product.name}}</p></div>
                                <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
                                <div style="flex:1">
                                    <p class="quantity">{{item.quantity}}</p>
                                    <div class="quantity">
                                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

                                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                                    </div>
                                </div>
                                <div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
                            </div>
                        {% endif %}
                        {% if  Women_Pants_product.product_name == ""%}
                        {% else %}
                            <div class="cart-row">
                                <div ><img class="row-image" src="{{item.product.imageURL}}"></div>
                                <div style="flex:2"><p>{{item.product.name}}</p></div>
                                <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
                                <div style="flex:1">
                                    <p class="quantity">{{item.quantity}}</p>
                                    <div class="quantity">
                                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

                                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                                    </div>
                                </div>
                                <div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
                            </div>
                        {% endif %}
                        {% if  Women_Pants_product.product_name == ""%}
                        {% else %}
                            <div class="cart-row">
                                <div ><img class="row-image" src="{{item.product.imageURL}}"></div>
                                <div style="flex:2"><p>{{item.product.name}}</p></div>
                                <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
                                <div style="flex:1">
                                    <p class="quantity">{{item.quantity}}</p>
                                    <div class="quantity">
                                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

                                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                                    </div>
                                </div>
                                <div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
                            </div>
                        {% endif %}
                    {% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

templates/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/contact.html
<!DOCTYPE html>
<title>Home Page</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
</style>
<body>

<!-- Top menu -->
<div class="w3-top">
  <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
    <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
    <div class="w3-center w3-padding-16">BOOM</div>
  </div>
</div>



<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">
    {% include 'navbar.html' %}

   <!-- About Section -->
  <div class="w3-container w3-padding-32 w3-center">
    <h3>For inquiries about becoming a seller and diplaying goods<decided></decided></h3><br>
{#    <img src="..." alt="Me" class="w3-image" style="display:block;margin:auto" width="800" height="533">#}
    <div class="w3-padding-32">
      <h6><i>Please contact admin@gmail.com we will review your application and if approved we will let you have an admin accountx</i></h6>
    </div>
  </div>
  <hr>

  <!-- Footer -->
  <footer class="w3-row-padding w3-padding-32">
    <div class="w3-third">
      <h3>About creators</h3>
      <p>Both of us played R6 for the whole night and failed calc oh ya we also went outside on the ice rink but we still failed calc</p>
    </div>

    <div class="w3-third">
      <h3>Maybe Somethin here</h3>
      <ul class="w3-ul w3-hoverable">
        <li class="w3-padding-16">
{#          <img src="/w3images/workshop.jpg" class="w3-left w3-margin-right" style="width:50px">#}
          <span class="w3-large">Wubba</span><br>
          <span>Nice pics maybe</span>
        </li>
        <li class="w3-padding-16">
{#          <img src="/w3images/gondol.jpg" class="w3-left w3-margin-right" style="width:50px">#}
          <span class="w3-large">Lubba</span><br>
          <span>Nice pics maybe</span>
        </li>
      </ul>
    </div>

    <div class="w3-third w3-serif">
      <h3>POPULAR BRANDS</h3>
      <p>
        <span class="w3-tag w3-black w3-margin-bottom">Chanel</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Gucci</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fendi</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Salmon</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Prada</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Nike</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Adidas</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">IDK more compamies</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Huwawei</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">lol</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">LMFAO</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fish</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">HUH?</span>
      </p>
    </div>
  </footer>

<!-- End page content -->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}
</script>

</body>
</html>

templates/delete_view.html
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>

templates/index.html
<!DOCTYPE html>
<
<title>Home Page</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
</style>
<body>

<!-- Top menu -->
<div class="w3-top">
  <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
    <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
    <div class="w3-center w3-padding-16">BOOM</div>
  </div>
</div>



<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">
    {% include 'navbar.html' %}

  <!-- First Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" id="food">
    <div class="w3-quarter">
       <a href="/products/shirts">
        <img src="https://st.tsum.com/btrx/i/11/75/66/24//01_1526.jpg?u=1612906071" alt="Sandwich" style="width:100%">
        <h3>Women Shirts</h3>
       </a>
    </div>
    <div class="w3-quarter">
        <a href="/products/dress">
            <img src="https://st.tsum.com/btrx/i/11/85/00/17//01_1526.jpg?u=1614980610" alt="Steak" style="width:100%">
            <h3>Dress</h3>
        </a>
    </div>
    <div class="w3-quarter">
        <a href="/products/skirts">
            <img src="https://st.tsum.com/btrx/i/11/85/54/58//01_1526.jpg?u=1615067097" alt="Steak" style="width:100%">
            <h3>Skirts</h3>
        </a>
    </div>
    <div class="w3-quarter">
        <a href="/products/pants">
            <img src="https://st.tsum.com/btrx/i/11/73/89/87//01_1526.jpg?u=1612388777" alt="Steak" style="width:100%">
            <h3>Pants</h3>
        </a>
    </div>

  <!-- Second Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" id="food">
    <div class="w3-quarter">
       <a href="/products/shirts">
        <img src="https://st.tsum.com/btrx/i/11/69/89/42//01_1526.jpg?u=1611092180" alt="Sandwich" style="width:100%">
        <h3>T-Shirts</h3>
       </a>
    </div>
    <div class="w3-quarter">
        <a href="/products/sweatshirts">
            <img src="https://st.tsum.com/btrx/i/11/76/10/83//01_1526.jpg?u=1613051206" alt="Steak" style="width:100%">
            <h3>SweatShirts</h3>
        </a>
    </div>
    <div class="w3-quarter">
        <a href="/products/pants">
            <img src="https://st.tsum.com/btrx/i/11/72/99/40//01_1526.jpg?u=1612215903" alt="Steak" style="width:100%">
            <h3>M.Shirts</h3>
        </a>
    </div>
    <div class="w3-quarter">
        <a href="/products/pants">
            <img src="https://st.tsum.com/btrx/i/11/61/58/89//01_1526.jpg?u=1609018500" alt="Steak" style="width:100%">
            <h3>Jeans</h3>
        </a>
    </div>

  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">

      <a href="#" class="w3-bar-item w3-white w3-button"></a>

    </div>
  </div>

  <hr id="about">

  <!-- About Section -->
  <div class="w3-container w3-padding-32 w3-center">
    <h3>This website was desinged to be very simple to use and make the customer as happy as possible<decided></decided></h3><br>
{#    <img src="..." alt="Me" class="w3-image" style="display:block;margin:auto" width="800" height="533">#}
    <div class="w3-padding-32">
      <h4><b>Comapnies promise</b></h4>
      <h6><i>Here at Dan and Han co. we are determind to satisfy the customer</i></h6>
      <p>Company registered on the Moon (easter egg) <KOREA></KOREA></p>
    </div>
  </div>
  <hr>

  <!-- Footer -->
  <footer class="w3-row-padding w3-padding-32">
    <div class="w3-third">
      <h3>About creators</h3>
      <p>Both of us played R6 for the whole night and failed calc oh ya we also went outside on the ice rink but we still failed calc</p>
    </div>

    <div class="w3-third">
      <h3>Maybe Somethin here</h3>
      <ul class="w3-ul w3-hoverable">
        <li class="w3-padding-16">
{#          <img src="/w3images/workshop.jpg" class="w3-left w3-margin-right" style="width:50px">#}
          <span class="w3-large">Wubba</span><br>
          <span>Nice pics maybe</span>
        </li>
        <li class="w3-padding-16">
{#          <img src="/w3images/gondol.jpg" class="w3-left w3-margin-right" style="width:50px">#}
          <span class="w3-large">Lubba</span><br>
          <span>Nice pics maybe</span>
        </li>
      </ul>
    </div>

    <div class="w3-third w3-serif">
      <h3>POPULAR BRANDS</h3>
      <p>
        <span class="w3-tag w3-black w3-margin-bottom">Chanel</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Gucci</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fendi</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Salmon</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Prada</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Nike</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Adidas</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">IDK more compamies</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Huwawei</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">lol</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">LMFAO</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fish</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">HUH?</span>
      </p>
    </div>
  </footer>

<!-- End page content -->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}
</script>

</body>
</html>

templates/navbar.html
<div>
<!--this is to draken the urls when we are on them-->
    {% url 'public:index' as index_url%}
    <span>{% if request.path == index_url %}Home{% else %}<a href="{{ index_url}}"> Home</a>{% endif %}</span>
    {% url 'public:about' as about_url%}
    <span>{% if request.path == about_url %}About{% else %}<a href="{{ about_url }}"> About</a>{% endif %}</span>
    {% url 'public:contact' as contact_url%}
    <span>{% if request.path == contact_url %}Home{% else %}<a href="{{contact_url}}"> Contact</a>{% endif %}</span>
    <span style="float:right">
        {% if user.is_authenticated %}
            {% if user.is_staff %}
                <a href="admino">Admin </a>
                {% endif %}
            {% url 'accounts:profile' as profile_url %}
            <span>Hi {% if request.path == profile_url %}{{ user.username }}{% else %}<a href="{{ profile_url }}">{{ user.username }}</a>{% endif %}! </span>
            <span><a href="{% url 'accounts:logout' %}">Logout</a> </span>
            <a href="{% url 'public:cart' %}">
                <img src="https://florex.am/Themes/florex/Content/images/icon-cart.png" width="25" height="25">
            </a>
        {% else %}
            <span><a href="{% url 'accounts:login' %}">Login</a></span>
            <span><a href="{% url 'accounts:signup' %}">Sign up</a></span>
        {% endif %}
    </span>
</div>